"""Synthetic graining / thermal / wear scenario generator (Experiment 4, PLAN.md §5).

**This data is synthetic and weakly supervised.** It is generated by a reference
condition model with hand-set coefficients, chosen to be qualitatively consistent with
what is reported about graining (it forms on a cold tire under high slip energy and
cleans up once the surface reaches its working temperature). It is a demonstrator of
the model *structure*; it is not validated real motorsport graining, and no
quantitative claim about a real tire may be based on it.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import torch

from tire_nn.physics.pacejka import MFParams, pacejka_combined
from tire_nn.physics.thermal import ThermalParams, slip_power, thermal_rates
from tire_nn.physics.wear import effective_friction

__all__ = ["ReferenceCondition", "make_synthetic_graining"]


class ReferenceCondition:
    """Reference (ground-truth) condition model with explicit, readable coefficients."""

    def __init__(
        self,
        thermal: ThermalParams | None = None,
        T_opt: float = 360.0,
        T_width: float = 45.0,
        c_T: float = 0.35,
        k_wear: float = 0.1,
        k_grain: float = 0.35,
        wear_coeff: float = 4.0e-9,       # wear per Joule of slip energy [-/J]
        form_coeff: float = 2.0e-2,       # graining formation rate scale [1/s]
        clean_coeff: float = 1.0e-2,      # graining cleaning rate scale  [1/s]
        T_cold: float = 345.0,            # below this the surface is "cold"
        P_ref: float = 4000.0,
    ):
        self.thermal = thermal or ThermalParams()
        self.__dict__.update(
            T_opt=T_opt, T_width=T_width, c_T=c_T, k_wear=k_wear, k_grain=k_grain,
            wear_coeff=wear_coeff, form_coeff=form_coeff, clean_coeff=clean_coeff,
            T_cold=T_cold, P_ref=P_ref)

    def mu_scale(self, Ts, wear, g):
        x = (Ts - self.T_opt) / self.T_width
        base = np.clip(1.0 - self.c_T * x * x, 0.05, None)
        return float(effective_friction(torch.tensor(base, dtype=torch.float32),
                                        torch.tensor(float(wear)), torch.tensor(float(g)),
                                        self.k_wear, self.k_grain))

    def rates(self, Ts, Tc, wear, g, P, T_road, T_air):
        dTs, dTc = thermal_rates(*(torch.tensor(float(v)) for v in (Ts, Tc, P, T_road, T_air)),
                                 self.thermal)
        dwear = self.wear_coeff * P                                  # >= 0 by construction
        cold = max(self.T_cold - Ts, 0.0) / 50.0
        hot = max(Ts - self.T_cold, 0.0) / 50.0
        R_form = self.form_coeff * cold * (P / self.P_ref)           # cold + high slip energy
        R_clean = self.clean_coeff * hot                             # warm surface cleans up
        dg = (1.0 - g) * R_form - g * R_clean
        return float(dTs), float(dTc), dwear, dg


def make_synthetic_graining(
    T: int = 24000,
    dt: float = 0.05,
    vx: float = 45.0,
    Fz: float = 3000.0,
    mu: float = 1.4,
    T_road: float = 305.0,
    T_air: float = 298.0,
    noise_state: float = 0.0,
    seed: int = 0,
    reference: ReferenceCondition | None = None,
) -> pd.DataFrame:
    """A four-phase stint: cold aggressive start, hot stint, cool-down, hot recovery.

    Phases (each a quarter of the run):

    1. **cold + aggressive** — high slip on a cold surface: graining should form.
    2. **hot + aggressive** — the surface reaches its window: cleaning should overtake
       formation while wear keeps accumulating.
    3. **cool-down** — low slip, the surface cools toward the road temperature.
    4. **aggressive again** — with the accumulated wear, grip is permanently lower than
       in phase 2 even once the temperature recovers.
    """
    ref = reference or ReferenceCondition()
    rng = np.random.default_rng(seed)
    q = T // 4
    alpha = np.concatenate([
        np.full(q, 0.14), np.full(q, 0.14), np.full(q, 0.02), np.full(T - 3 * q, 0.14)])
    kappa = np.concatenate([
        np.full(q, 0.05), np.full(q, 0.05), np.full(q, 0.005), np.full(T - 3 * q, 0.05)])
    alpha += 0.01 * np.sin(np.arange(T) * dt * 0.7)

    px = MFParams(B=9.0, C=1.6, E=0.4, mu=mu, k_mu=0.08, Fz0=3000.0)
    py = MFParams(B=8.5, C=1.5, E=0.4, mu=mu, k_mu=0.08, Fz0=3000.0)

    Ts = Tc = 300.0
    wear = g = 0.0
    rows = []
    for i in range(T):
        scale = ref.mu_scale(Ts, wear, g)
        pxs = MFParams(B=px.B, C=px.C, E=px.E, mu=mu * scale, k_mu=px.k_mu, Fz0=px.Fz0)
        pys = MFParams(B=py.B, C=py.C, E=py.E, mu=mu * scale, k_mu=py.k_mu, Fz0=py.Fz0)
        Fx, Fy = pacejka_combined(torch.tensor([alpha[i]]), torch.tensor([kappa[i]]),
                                  torch.tensor([Fz]), pxs, pys)
        vsx, vsy = kappa[i] * vx, vx * np.tan(alpha[i])
        P = float(slip_power(Fx, Fy, torch.tensor([vsx]), torch.tensor([vsy])))

        rows.append({"t": i * dt, "sequence_id": 0, "alpha": alpha[i], "kappa": kappa[i],
                     "Fz": Fz, "vx": vx, "Fx": float(Fx), "Fy": float(Fy), "P_slip": P,
                     "Ts": Ts, "Tc": Tc, "wear": wear, "graining": g, "mu_scale": scale,
                     "T_road": T_road, "T_air": T_air,
                     "tire_id": "synthetic", "source": "synthetic"})

        dTs, dTc, dwear, dg = ref.rates(Ts, Tc, wear, g, P, T_road, T_air)
        Ts += dt * dTs
        Tc += dt * dTc
        wear += dt * dwear
        g = float(np.clip(g + dt * dg, 0.0, 1.0))

    df = pd.DataFrame(rows)
    if noise_state > 0:
        df["Ts_meas"] = df["Ts"] + rng.normal(0, noise_state * 5.0, len(df))
        df["graining_meas"] = np.clip(df["graining"] + rng.normal(0, noise_state * 0.05, len(df)), 0, 1)
    df.attrs["dt"] = dt
    df.attrs["reference"] = ref
    return df
