"""Sphinx configuration for tire_physics_nn (built by ReadTheDocs, see .readthedocs.yaml).

Deliberately dependency-light: the API reference uses sphinx-autoapi, which parses
``tire_nn/`` statically instead of importing it, so the docs build needs neither torch
nor a trained model. All figures are pre-generated by ``docs/generate_figures.py`` and
committed under ``_static/figures/`` — regenerate them with ``make figures`` after
changing a model or a default.
"""

import os
import sys

sys.path.insert(0, os.path.abspath("../.."))

project = "tire_physics_nn"
author = "Agnes Poks"
copyright = "2026, Agnes Poks"
release = "0.1.0"

extensions = [
    "myst_parser",
    "sphinx.ext.napoleon",   # parse the Google-style Args:/Returns: blocks in the docstrings
    "nbsphinx",
    "nbsphinx_link",
    "autoapi.extension",
    "sphinxcontrib.bibtex",
]

source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
myst_enable_extensions = ["dollarmath", "amsmath", "colon_fence", "deflist"]
myst_heading_anchors = 3

nbsphinx_execute = "never"

autoapi_type = "python"
autoapi_dirs = ["../../tire_nn"]
autoapi_add_toctree_entry = True
autoapi_keep_files = False
autoapi_options = ["members", "undoc-members", "show-inheritance", "show-module-summary"]

bibtex_bibfiles = ["../../papers/references.bib"]
bibtex_default_style = "plain"

html_theme = "sphinx_rtd_theme"
html_title = "tire_physics_nn"
html_static_path = ["_static"]
# The RTD sidebar is dark, so the light-text wordmark is the one that belongs there.
# Regenerate all logo assets with: python docs/make_logo.py
html_logo = "_static/logo-dark.svg"
html_favicon = "_static/favicon.png"
html_theme_options = {"logo_only": True, "style_external_links": True}

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# README.md and PLAN.md are included verbatim; their GitHub-relative links are correct
# on GitHub but are not resolvable Sphinx targets. Cosmetic only.
suppress_warnings = ["myst.xref_missing"]
